-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "country" TEXT DEFAULT 'IN';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'INR';

-- AlterTable
ALTER TABLE "DemoSession" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'INR';

-- AlterTable
ALTER TABLE "WebinarRegistration" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'INR';

-- AlterTable
ALTER TABLE "LmsEnrollment" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'INR';
